code_index:
    resource: "@ClassroomProjectBundle/Controller/IndexController.php"
    type: annotation

code_project:
    resource: "@ClassroomProjectBundle/Controller/ProjectController.php"
    type: annotation

code_class:
    resource: "@ClassroomProjectBundle/Controller/NodeController.php"
    type: annotation
